#!/bin/sh

. /etc/sysconfig/bootstrap_admin_node

if test "${ENABLED}" = "1"; then
    echo "ENABLED=0" > /etc/sysconfig/bootstrap_admin_node
    /usr/local/sbin/bootstrap_admin_node.sh 2>&1 | tee /var/log/puppet/bootstrap_admin_node.log
fi
